# Generated by Django 2.2.3 on 2019-08-04 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('categoryId', models.PositiveIntegerField(default=58058)),
            ],
        ),
        migrations.AddField(
            model_name='recent',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='predictor.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='predictor.category'),
            preserve_default=False,
        ),
    ]
