# Generated by Django 2.2.3 on 2019-08-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20190804_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=models.PositiveIntegerField(default=175673),
        ),
    ]
